### ISSUE TITLE
dailyQuotaResetTime range 0 to 23

### ISSUE THREAD

**Issue by rfcdejong** [Azure/Health-Data-and-AI-Blueprint#12]
In the description the range is set from 0 to 23, however the default value is 24. This confuses me, is 24 allowed or not?

**Comment by jomolesk** [comment]
Based on the parameter description -- "Enter daily quota reset hour in UTC (0 to 23). Values outside the range will get a random reset hour." -- 24 is a valid value that will result in a random reset hour. If you'd like more information, please follow up here: https://docs.microsoft.com/en-us/azure/azure-monitor/app/powershell
